site_name: Resources
site_author: Lennart Wittkuhn
repo_url: https://github.com/lnnrtwttkhn/resources
site_url: https://lnnrtwttkhn.github.io/resources/
repo_name: lnnrtwttkhn/resources
edit_uri: edit/master/docs/
docs_dir: docs
copyright: 'Copyright &copy 2021 Lennart Wittkuhn'
nav:
  - Home: index.md
  - Blogs: blogs.md
  - Coding: coding.md
  - Documentation: documentation.md
  - Data Managament: data-management.md
  - Data collection: data-collection.md
  - Datasets: datasets.md
  - Education: education.md
  - Events: events.md
  - Fun: fun.md
  - Git: git.md
  - Modeling: modeling.md
  - Open Science: open-science.md
  - Productivity: productivity.md
  - Neuroimgaing: neuroimaging.md
  - Science: science.md
  - Statistics: statistics.md
markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        baselevel: 1
        permalink: true
        separator: "_"
        toc_depth: 3
        anchorlink: false
theme:
    name: material
    language: en
plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        timezone: Europe/Amsterdam
        locale: en
        fallback_to_build_date: false
